version: 0.2

phases:
  install:
    commands:
      - echo $Repo
      - echo $Action
      - git clone https://github.com/$Repo
  build:
    commands:
      - cd aws-journey/labs
      - ls
      - terraform --version
      # - ./deploy_lab.sh ${Action} ${Lab} ${StateBucket} ${StateTable}
