version: 0.2

phases:
  install:
    commands:
      - echo $REPO
      - echo $ACTION
      - git clone https://github.com/$Repo
  build:
    commands:
      - cd aws-journey/labs
      - ./deploy_lab.sh
      - terraform --version
      # - ./deploy_lab.sh ${Action} ${Lab} ${StateBucket} ${StateTable}
