version: 0.2

phases:
  build:
    on-failure: ABORT
    commands:
      - cd /aws-journey/labs/$LAB_ID/iac
      - if [[ -f pre_deploy.sh ]]; then ./pre_deploy.sh; fi
      - cd /aws-journey/labs/deploy_lab
      - ./deploy_lab_script
      - echo FINISHED
