version: 0.2

phases:
  build:
    commands:
      - cd /apps/labs/$LAB_ID/iac/
      - rm -rf .terraform .terraform.lock.hcl backend.tf provider.tf
      - cd /apps/labs/deploy_lab
      - ./deploy_lab_script
      - echo FINISHED
